### ISSUE TITLE
Investigate colorama for colorizing output

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#33]
Probably better to use an external library than to put in ANSI escape sequences ourselves. See https://pypi.python.org/pypi/colorama.

**Comment by shweta97** [comment]
While researching about it, I found out that colorama is not an external library for ANSI escape sequences. Instead it is to make ANSI escape sequences work for Windows. If colorama is not used then in Windows the ANSI sequences are printed to the console. I think you mentioned that Dan Zinger faced the same problem. If I remember correctly he uses Windows and maybe had an issue due to this.

**Comment by nigef** [comment]
*Dan Zingaro

**Comment by david-yz-liu** [comment]
Fixed in #59.
