### ISSUE TITLE
Create plain (no-colour) reporter

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#34]
Dan Zingaro reports that his screen reader reads the ANSI symbols required to colorize the PyTA report text, which isn't good.

We should create two different reporter classes, one which colorizes, and one which doesn't.

**Comment by shweta97** [comment]
I think the reason that Dan Zingaro's  screen reads the ANSI symbols is because ANSI escape sequences do not work on Windows. I remember him mentioning last meeting that he uses Windows. If so, I suggest that we use colorama to make the ANSI sequences work properly on Windows instead of creating two reporter classes.

**Comment by david-yz-liu** [comment]
Fixed #59.
