### ISSUE TITLE
PyTA thinks comprehension scope is shared with function scope

### ISSUE THREAD

**Issue by eamonma** [pyta-uoft/pyta#657]
For example, the following code is perfectly valid. However, PyTA raises errors `E9969 (possibly-undefined)` and `E9988 (shadowing-inside-comprehension)`, even though the loop variable is in a different scope from the comprehension variable.

```
from typing import List


def example(example_list: List[int]) -> None:
    new_list = [same_name / 1 for same_name in example_list]

    for same_name in new_list:
        useless = same_name


if __name__ == '__main__':
    import python_ta

    python_ta.check_all(config={
        'max-line-length': 100,
        'extra-imports': ['dataclasses', 'python_ta.contracts'],
        'disable': ['C0116', "C0114"]
    })

    import python_ta.contracts

    python_ta.contracts.DEBUG_CONTRACTS = False
    python_ta.contracts.check_all_contracts()
```

**Comment by kavins14** [comment]
Hi, my understanding is that error `E9988 (shadowing-inside-comprehension)` is there to prevent students from using the same variable name inside the comprehension as well as outside, as it can be considered as bad practice. This is in spite of the fact that the loop variable and comprehension variable are in different scopes.

I did some research as to why error E9969 (possibly-undefined) is raised, and this is what I found:
*  astroid does not consider the variable `same_name` inside the comprehension as a local variable, which is correct. And so the checker algorithm considers `same_name` as possible undefined because it thinks `same_name` refers to a local variable and not a variable in the comprehension scope. If `same_name` was not a local variable in the first place, this error would not be raised.
* One way to avoid this issue is to check if every variable `n` that is possible undefined is being used inside a comprehension that defines `n`. If so, we don't consider it possibly undefined.

I might create a PR within a couple of weeks to resolve this issue.
