### ISSUE TITLE
Add Pylint v2.10.0 checkers to Pylint examples

### ISSUE THREAD

**Issue by ckatsube** [pyta-uoft/pyta#750]
Pylint v2.10.0 was released 4 hours ago (8/20/2021) and introduced some new checkers

If you're working on this, make sure to add the checker to `docs/checkers/index.md`, too.

# New Checker List:
- [ ] W1514-unspecific-encoding
- [ ] R1734-use-list-literal
- [ ] R1735-use-dict-literal
- [ ] W1515-forgotten-debug-statement
- [ ] W1310-format-string-without-interpolation
- [ ] W1406-redundant-u-string-prefix
- [ ] C0208-use-sequence-for-iteration

# Link to v2.10.0 release changelogs:
https://github.com/PyCQA/pylint/releases/tag/v2.10.0
https://github.com/PyCQA/pylint/blob/main/doc/whatsnew/2.10.rst

# Links to commits (in respective order):
W1514 https://github.com/PyCQA/pylint/commit/a8b7dd7bffe343f00bcd6409534edcab530a4fc4
R1734 and R1735 https://github.com/PyCQA/pylint/commit/23412dc98f895a0262119320e54ad78ec4e108bc
W1515 https://github.com/PyCQA/pylint/commit/5e5f48d05fb6f1322a7420d6ea7586966b08f80a
W1310 https://github.com/PyCQA/pylint/commit/ea7f39e3ab82de36ce0becc6d70151d862c807dc
W1406 https://github.com/PyCQA/pylint/commit/865765ca78b43829d98c6c4424b6364c63925186
C0208 https://github.com/PyCQA/pylint/commit/61b4db0dc31fd31fcfda36e4730cb44848af2d30

**Comment by ckatsube** [comment]
Actually wait how should I go about this since PyTA has a `pylint < 2.10` restriction. I guess maybe this should be an Upgrade to Pylint 2.10 PR instead of these individual ones.

**Comment by david-yz-liu** [comment]
@ckatsube I generally review the new pylint releases and checkers when they come out, and decide which ones to keep and which ones to disable by default. An issue isn't the right place to track these, we've been using this wiki page instead: https://github.com/pyta-uoft/pyta/wiki/Pylint-Checker-Tracking. If you like you can add these checkers to that page (put down "to be reviewed" or something), so that we have a record of them to add examples for in the future!
